---
orc8r_domain: ""
magma_namespace: "orc8r"
magma_docker_registry: "linuxfoundation.jfrog.io/magma-docker"
magma_docker_tag: "1.8.0"
magma_directory: "magma-galaxy"
magma_service_type: "ClusterIP"
orc8r_db_driver: "postgres"
orc8r_db_name: "magma"
orc8r_db_host: "postgresql"
orc8r_db_port: "5432"
orc8r_db_user: "postgres"
orc8r_db_pass: "postgres"
deploy_wifi_orc8r: false
deploy_domain_proxy: false
deploy_fbinternal_orc8r: false
